### ISSUE TITLE
[최용권] 배너 선택시 화면전환을 위한 스크린경로를 추가하여 응답한다

### ISSUE THREAD

**Issue by hiYong94** [BorryJJong/KnockKnock-API#265]

**Comment by hiYong94** [comment]
@dy-yb 배너 선택시 이동하는 화면 정해졌는데요, 해당 부분 추천하시는 컨벤션 있을까요? 🤔

**Comment by dy-yb** [comment]
> @dy-yb 배너 선택시 이동하는 화면 정해졌는데요, 해당 부분 추천하시는 컨벤션 있을까요? 🤔

특정 챌린지 화면으로 이동하는 경우 CHALLENGE_challengeId(ex, CHALLENGE_13) 형식으로 하고,
피드 작성 화면은 FEED_WRITE로 해주시면 어떨까요?

**Comment by hiYong94** [comment]
@dy-yb 음.. 인덱스가 바뀔수도 있는걸 고려해서, `name`으로하는건 어떨까요?
`ex) CHALLENGE_GOGO`

피드 작성 화면은 좋습니다!

**Comment by dy-yb** [comment]
@hiYong94 넵넵 그렇게 하시죠

**Comment by hiYong94** [comment]
@dy-yb 노션 콘텐츠 페이지에 스크린 이동 내용 추가하였습니다!
[녹녹콘텐츠](https://www.notion.so/69bc5b2a14f94bfaa7f678f823a930b4?pvs=4)
